name: speedtest
description: A UI demo for speedtest application.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_speedometer: ^1.0.2
  introduction_screen: ^1.0.8
  font_awesome_flutter: ^8.8.1
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
